export const GET_RECENT = "GET_RECENT";
export const GET_RECENT_SUCCESS = "GET_RECENT_SUCCESS";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const UPDATE_QUANTITY = "UPDATE_QUANTITY";
export const ADD_ITEM = "ADD_ITEM";
